id: P000225
initial_creation_type: ebook
source_metadata:
  title: ༄༅། །སྡོམ་པ་གསུམ་གྱི་རྒྱན་ཅེས་བྱ་བའི་རྒྱ་ཆེར་འགྲེལ་ལས་ལེའུ་དང་པོ་བཞུགས་སོ།
    །
  authors:
  - མཛད་པ་པོ། ཀུན་མཁྱེན་པདྨ་དཀར་པོ་།
  layers:
  - book_title
  - author
  - tsawa
  - quotation
  - sabche
  id: KS-PK-14
web_metadata:
  title:
    en: An Extensive Commentary on the Ornament for the Three Sets of Vows:Chapter
      1
    bo: སྡོམ་པ་གསུམ་གྱི་རྒྱན་ཅེས་བྱ་བའི་རྒྱ་ཆེར་འགྲེལ་ལས་ལེའུ་དང་པོ་བཞུགས་སོ། །
  collection:
    en: Pema Karpo Series–  Book 14
    bo: ཀུན་མཁྱེན་གཞུང་འགྲེལ།–  དེབ། ༡༤
  author:
    en: Kunkhyen Pema Karpo
    bo: ཀུན་མཁྱེན་པདྨ་དཀར་པོ།
  pusblisher:
    en: Gautam Buddha Vihara
    bo: དོན་བརྒྱུད་དཔལ་ལྡན་འབྲུག་པ།
  sku: KS-PK-14
  category:
    en: Three Vows
    bo: སྡོམ་གསུམ།
  org:
    bo: Timeless Treasuries
    en: མཐའ་ཡས་དཔེ་མཛོད།
  website: http://dharmacloud.tsadra.org
  aquisition_data: '2019-07-18'
  filename: KS-PK-14.epub
  description:
    en: ''
    bo: ''
